[package]
name = "ot"
version = "0.1.0"
authors = ["Dustin J. Mitchell <dustin@mozilla.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = { version = "0.8.1", features = ["serde", "v4"] }
serde = "1.0.104"
serde_json = "1.0"
chrono = { version = "0.4.10", features = ["serde"] }
failure = {version = "0.1.5", features = ["derive"] }
clap = "~2.33.0"

[dev-dependencies]
proptest = "0.9.4"
