[package]
name = "taskchampion-cli"
version = "0.1.0"
authors = ["Dustin J. Mitchell <dustin@mozilla.com>"]
edition = "2018"

[dependencies]
clap = "~2.33.0"
taskchampion = { path = "../taskchampion" }
failure = "0.1.8"
prettytable-rs = "0.8.0"

[dev-dependencies]
assert_cmd = "1.0.1"
predicates = "1.0.5"
