[book]
authors = ["Dustin J. Mitchell"]
language = "en"
multilingual = false
src = "src"
title = "TaskChampion"

[output.html]
default-theme = "ayu"

[preprocessor.usage-docs]
command = "target/debug/usage-docs"
